nodeLinker: node-modules

npmRegistries:
  //gitlab.ptm.net/api/v4/packages/npm/:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_PACKAGE_TOKEN}"

npmScopes:
  ptm:
    npmRegistryServer: "https://gitlab.ptm.net/api/v4/packages/npm/"

yarnPath: .yarn/releases/yarn-3.6.0.cjs
